"""The contract between the Node backend and this service.

Node's `scraperServiceClient.ts` depends on these shapes; changing a field here
means changing it there too.

Deliberate boundary: this service returns RAW NORMALISED DATA ONLY. No AI
enrichment, no scoring, no database writes. Classification, summarisation and
scoring all happen in Node, which keeps OpenAI spend and prompt versioning in one
place and leaves this service stateless and easy to replace.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ScrapeErrorReason(str, Enum):
    """Why a single target failed. `robots_disallowed` is a normal outcome, not a bug."""

    ROBOTS_DISALLOWED = "robots_disallowed"
    TIMEOUT = "timeout"
    PARSE_ERROR = "parse_error"
    HTTP_ERROR = "http_error"
    # 401, or a page whose body says "please sign in".
    LOGIN_REQUIRED = "login_required"
    # 403 — typically a WAF or bot-detection layer refusing our honest
    # User-Agent. Kept distinct from LOGIN_REQUIRED because the remedy differs:
    # a blocked target should be dropped from the target list, not credentialed.
    # We do not spoof a browser User-Agent to get around this.
    BLOCKED = "blocked"
    UNKNOWN = "unknown"


class ScrapeStatus(str, Enum):
    COMPLETED = "completed"
    PARTIAL = "partial"  # Some targets succeeded, some failed.
    FAILED = "failed"


class ScrapeOptions(BaseModel):
    max_pages_per_target: int = Field(default=5, ge=1, le=50)
    respect_robots_txt: bool = True
    timeout_sec_per_page: int = Field(default=20, ge=1, le=120)

    # Many faculty index pages list no email, but the linked profile page does.
    # Following that link is the difference between a lead you can contact and
    # one you cannot — which matters most for Indian institutes, where index
    # pages almost never publish addresses.
    follow_profiles: bool = True
    # Bounded because each fetch costs a rate-limit delay against the same domain.
    max_profile_fetches: int = Field(default=20, ge=0, le=100)

    # Escalate to a real browser when a cheap fetch returns nothing usable.
    # Set false for a fast, low-cost run that only uses plain HTTP.
    allow_browser: bool = True
    # Escalate further to a proxied browser for IP-reputation blocks. No effect
    # unless proxy credentials are configured in the environment.
    allow_proxy: bool = True


class FacultyTarget(BaseModel):
    university_name: str
    faculty_page_url: str


class NewsTarget(BaseModel):
    university_name: str
    news_page_url: str


class ScrapeRequest(BaseModel):
    """`job_id` is generated by Node and echoed back, so runs can be traced across services."""

    job_id: str
    options: ScrapeOptions = Field(default_factory=ScrapeOptions)


class FacultyScrapeRequest(ScrapeRequest):
    targets: list[FacultyTarget]


class NewsScrapeRequest(ScrapeRequest):
    targets: list[NewsTarget]


class ExtractedPerson(BaseModel):
    """A person found on a faculty page. Every field beyond `name` is best-effort."""

    name: str
    title: Optional[str] = None
    department: Optional[str] = None
    email: Optional[str] = None
    profile_url: Optional[str] = None
    bio: Optional[str] = None


class ExtractedNewsItem(BaseModel):
    title: str
    url: Optional[str] = None
    published_at: Optional[datetime] = None
    summary: Optional[str] = None
    # Names mentioned in the article — Node cross-references these against known leads.
    mentioned_names: list[str] = Field(default_factory=list)


class ScrapeError(BaseModel):
    target: str
    reason: ScrapeErrorReason
    detail: Optional[str] = None


class FacultyScrapeResult(BaseModel):
    source_url: str
    university_name: str
    extracted: list[ExtractedPerson] = Field(default_factory=list)
    scraped_at: datetime
    # Which tier produced this result: "static", "browser", or "browser+proxy".
    # Surfaced so it is obvious when a target is quietly costing a browser launch
    # on every run and should be reviewed.
    fetch_tier: str = "static"


class NewsScrapeResult(BaseModel):
    source_url: str
    university_name: str
    extracted: list[ExtractedNewsItem] = Field(default_factory=list)
    scraped_at: datetime


class FacultyScrapeResponse(BaseModel):
    job_id: str
    status: ScrapeStatus
    results: list[FacultyScrapeResult] = Field(default_factory=list)
    # Per-target isolation: one broken site never fails the whole run.
    errors: list[ScrapeError] = Field(default_factory=list)


class NewsScrapeResponse(BaseModel):
    job_id: str
    status: ScrapeStatus
    results: list[NewsScrapeResult] = Field(default_factory=list)
    errors: list[ScrapeError] = Field(default_factory=list)


class HealthResponse(BaseModel):
    status: str
    service: str
    robots_enforcement: bool
    request_delay_ms: int


# ---------------------------------------------------------------------------
# Per-lead enrichment (profile page, ORCID, lab website) and paper reading
# ---------------------------------------------------------------------------


class EnrichLeadOptions(BaseModel):
    timeout_sec_per_page: int = Field(default=20, ge=1, le=120)
    # Every fetch waits on a per-domain delay, so the page budget is what
    # bounds how long one lead can take.
    max_pages: int = Field(default=8, ge=1, le=30)
    follow_lab_sites: bool = True
    use_orcid: bool = True
    allow_browser: bool = True


class EnrichLeadRequest(BaseModel):
    job_id: str
    name: str
    institution_name: Optional[str] = None
    orcid: Optional[str] = None
    # A profile page already known (an institute page, not an OpenAlex URL).
    profile_url: Optional[str] = None
    # Faculty directory pages for this person's institute, from Node's settings.
    directory_urls: list[str] = Field(default_factory=list)
    # Brand and model names to look for; sentences mentioning any are returned.
    instrument_terms: list[str] = Field(default_factory=list)
    options: EnrichLeadOptions = Field(default_factory=EnrichLeadOptions)


class TextSnippet(BaseModel):
    url: str
    text: str


class EnrichLeadResponse(BaseModel):
    job_id: str
    # Whether the institute directory was read, and whether it listed the
    # person. A directory that has dropped them is the most current sign of a
    # move there is; Node folds it into the affiliation status.
    directory_checked: bool = False
    directory_listed: Optional[bool] = None
    profile_url: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    designation: Optional[str] = None
    department: Optional[str] = None
    websites: list[str] = Field(default_factory=list)
    snippets: list[TextSnippet] = Field(default_factory=list)
    pages_visited: list[str] = Field(default_factory=list)
    errors: list[ScrapeError] = Field(default_factory=list)


class PaperRef(BaseModel):
    id: str
    url: str
    title: Optional[str] = None


class PaperTextRequest(BaseModel):
    job_id: str
    papers: list[PaperRef]
    instrument_terms: list[str] = Field(default_factory=list)
    timeout_sec_per_page: int = Field(default=30, ge=1, le=180)


class PaperTextResult(BaseModel):
    id: str
    url: str
    kind: str  # "pdf" | "html"
    chars: int
    snippets: list[str] = Field(default_factory=list)
    # Addresses printed in the author block — the corresponding author's email
    # is often the only published one for a researcher. Node picks the one
    # that echoes the lead's name.
    emails: list[str] = Field(default_factory=list)


class PaperTextResponse(BaseModel):
    job_id: str
    results: list[PaperTextResult] = Field(default_factory=list)
    errors: list[ScrapeError] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Affiliation check via registries (IRINS, Vidwan) and the institute directory
# ---------------------------------------------------------------------------


class RegistrySpec(BaseModel):
    key: str
    label: str
    # A search URL with {name} where the URL-encoded name goes.
    search_url: str


class AffiliationRequest(BaseModel):
    job_id: str
    name: str
    institution_name: Optional[str] = None
    # Institute names to recognise on a profile page when no field is labelled.
    known_institutions: list[str] = Field(default_factory=list)
    directory_urls: list[str] = Field(default_factory=list)
    registries: list[RegistrySpec] = Field(default_factory=list)
    timeout_sec_per_page: int = Field(default=20, ge=1, le=120)
    allow_browser: bool = True


class AffiliationHit(BaseModel):
    source: str
    profile_url: str
    matched_name: str
    institution: Optional[str] = None
    department: Optional[str] = None
    designation: Optional[str] = None
    detail: Optional[str] = None


class AffiliationResponse(BaseModel):
    job_id: str
    directory_checked: bool = False
    directory_listed: Optional[bool] = None
    directory_url: Optional[str] = None
    hits: list[AffiliationHit] = Field(default_factory=list)
    errors: list[ScrapeError] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Faculty-page discovery for the roster build
# ---------------------------------------------------------------------------


class InstitutionRoot(BaseModel):
    name: str
    homepage_url: str


class FindFacultyPagesRequest(BaseModel):
    job_id: str
    institutions: list[InstitutionRoot]
    # Department name fragments to follow: "chem", "bio", "material", ...
    department_hints: list[str] = Field(default_factory=list)
    max_probes_per_institution: int = Field(default=30, ge=1, le=80)
    timeout_sec_per_page: int = Field(default=20, ge=1, le=120)


class FoundFacultyPage(BaseModel):
    url: str
    department: Optional[str] = None
    people: int = 0
    emails: int = 0
    profiles: int = 0
    sample: list[str] = Field(default_factory=list)
    hop: int = 1


class FindFacultyPagesResult(BaseModel):
    institution: str
    pages: list[FoundFacultyPage] = Field(default_factory=list)
    error: Optional[str] = None
    detail: Optional[str] = None


class FindFacultyPagesResponse(BaseModel):
    job_id: str
    results: list[FindFacultyPagesResult] = Field(default_factory=list)
